# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='cost',
        ),
    ]
